// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailDemo.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(RetailDbContext))]
    [Migration("20251106191353_ConfigureDecimalPrecision")]
    partial class ConfigureDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetailDemo.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9a5b9a7-5d1f-4b0e-9d2a-1b3e4c6f8a9b"),
                            ProductId = new Guid("9a477379-320d-4a43-a47b-3058887f5f3c"),
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("d8b6c8b6-6e2f-4c1f-af3b-2c4f5d7e9b8d"),
                            ProductId = new Guid("ae80925f-441d-449a-a14a-528656594867"),
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("e7c7d7c5-7f3f-4d2e-be4c-3d5e6f8dab7e"),
                            ProductId = new Guid("f7317540-7a8c-49a9-9a3c-90a0e759a2d4"),
                            Stock = 20
                        });
                });

            modelBuilder.Entity("RetailDemo.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RetailDemo.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a477379-320d-4a43-a47b-3058887f5f3c"),
                            Category = "Electronics",
                            Name = "Laptop",
                            Price = 1200m
                        },
                        new
                        {
                            Id = new Guid("ae80925f-441d-449a-a14a-528656594867"),
                            Category = "Electronics",
                            Name = "Headphones",
                            Price = 150m
                        },
                        new
                        {
                            Id = new Guid("f7317540-7a8c-49a9-9a3c-90a0e759a2d4"),
                            Category = "Home Appliances",
                            Name = "Coffee Maker",
                            Price = 80m
                        });
                });

            modelBuilder.Entity("RetailDemo.Models.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("RetailDemo.Models.InventoryItem", b =>
                {
                    b.HasOne("RetailDemo.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RetailDemo.Models.Recommendation", b =>
                {
                    b.HasOne("RetailDemo.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
